language: c

os:
    - linux
    - osx

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then brew update             ; fi

install:
    - wget "http://www.creytiv.com/pub/re-0.4.17.tar.gz"
    - tar -xzf re-0.4.17.tar.gz
    - cd re-0.4.17 && make && sudo make install && cd ..
    - git clone https://github.com/alfredh/rew.git
    - cd rew && make && sudo make install && cd ..
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ldconfig ; fi
    - wget "https://github.com/alfredh/pytools/raw/master/ccheck.py"

script: 
    - make EXTRA_CFLAGS=-Werror
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python2 ccheck.py ; fi
